<testsuite name="OSMO Test Suite" timestamp="01.01.1970 00:00:01" hostname="OSMO rules" tests="7" failures="0" errors="1" time="2.00">
  <properties>
    <property name="Algorithm" value="osmo.tester.generator.algorithm.RandomAlgorithm"/>
    <property name="Listener" value="osmo.tester.reporting.jenkins.JenkinsReportGenerator"/>
    <property name="Model Object" value="osmo.tester.unittests.testmodels.ErrorModel5"/>
    <property name="Seed" value="-8811822948555199407"/>
    <property name="Suite End Condition" value="And{conditions=[Length{length=1}, Probability{threshold=0.05}]}"/>
    <property name="Test Case End Condition" value="And{conditions=[Length{length=1}, Probability{threshold=0.1}]}"/>
  </properties>
  <testcase name="Test1_step_1_hello" classname="osmo.tester.unittests.testmodels.ErrorModel5" time="0.00">
  </testcase>
  <testcase name="Test1_step_2_hello" classname="osmo.tester.unittests.testmodels.ErrorModel5" time="0.00">
  </testcase>
  <testcase name="Test1_step_3_hello" classname="osmo.tester.unittests.testmodels.ErrorModel5" time="0.00">
  </testcase>
  <testcase name="Test2_step_1_hello" classname="osmo.tester.unittests.testmodels.ErrorModel5" time="0.00">
  </testcase>
  <testcase name="Test2_step_2_hello" classname="osmo.tester.unittests.testmodels.ErrorModel5" time="0.00">
  </testcase>
  <testcase name="Test2_step_3_hello" classname="osmo.tester.unittests.testmodels.ErrorModel5" time="0.00">
  </testcase>
  <testcase name="Test2_step_4_hello" classname="osmo.tester.unittests.testmodels.ErrorModel5" time="0.00">
    <error message="string" type="string">java.lang.Exception: java.lang.AssertionError: @TestStep assert fail
	at osmo.tester.reporting.jenkins.JenkinsReportGenerator.testError(JenkinsReportGenerator.java:132)
	at osmo.tester.generator.listener.GenerationListenerList.testError(GenerationListenerList.java:108)
	at osmo.tester.generator.MainGenerator.handleError(MainGenerator.java:225)
	at osmo.tester.generator.MainGenerator.nextTest(MainGenerator.java:165)
	at osmo.tester.generator.MainGenerator.generate(MainGenerator.java:98)
	at osmo.tester.OSMOTester.generate(OSMOTester.java:90)
	at osmo.tester.unittests.reporting.jenkins.ReportTests.testError(ReportTests.java:182)
	at osmo.tester.unittests.reporting.jenkins.ReportTests.error5Tests2(ReportTests.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.AssertionError: @TestStep assert fail
	at osmo.tester.unittests.testmodels.ErrorModel5.transition1(ErrorModel5.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at osmo.tester.model.InvocationTarget.invoke(InvocationTarget.java:39)
	at osmo.tester.generator.MainGenerator.execute(MainGenerator.java:295)
	at osmo.tester.generator.MainGenerator.nextStep(MainGenerator.java:276)
	at osmo.tester.generator.MainGenerator.nextTest(MainGenerator.java:159)
	... 27 more
 </error>
  </testcase>
  <system-out></system-out>
  <system-err></system-err>
</testsuite>

